-- EFS-DB-002 v2.0
-- V134 - Playbook Schema Privileges

GRANT USAGE ON SCHEMA playbook TO efs_app;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA playbook
TO efs_app;

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA playbook
TO efs_app;