default_vhost = /

default_user = $(EFS_RABBITMQ_USERNAME)
default_pass = $(EFS_RABBITMQ_PASSWORD)

default_user_tags.administrator = false

default_permissions.configure = ^(efs\.domain\.events|risk-engine\.scenario-activated|risk-engine\.scenario-activated\.dlq|alert-engine\.decision-generated|alert-engine\.decision-generated\.dlq|notification-service\.notification-requested|notification-service\.notification-requested\.dlq)$

default_permissions.read = ^(efs\.domain\.events|amq\.default|risk-engine\.scenario-activated|alert-engine\.decision-generated|notification-service\.notification-requested)$

default_permissions.write = ^(efs\.domain\.events|risk-engine\.scenario-activated|alert-engine\.decision-generated|notification-service\.notification-requested)$